version: '3.8'

services:
  db:
    container_name: milton_compose
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: junior123
      POSTGRES_USER: postgres
    volumes:
      - C:\sesp\env\postgres_container_data:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: ficdev_compose
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: junior123
    depends_on:
      - db
    restart: always